[package]
name = "moonwalk"
version = "0.1.2"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pollster = "0.3"
bytemuck = { version = "1.13", features = ["derive"] }
env_logger = "0.10"
glam = { version = "0.24", features = ["scalar-math", "bytemuck"] }
cosmic-text = "0.8"
swash = "0.1"
rustc-hash = "1.1"
thiserror = "1.0"
image = {version = "0.24", default-features = false, features = ["png", "jpeg", "webp"]}
libc = "0.2"
raw-window-handle = "0.6"
winit = { version = "0.30", features = ["rwh_06"] }  # если используешь winit; подставь свою версию
wgpu = "0.20"