[package]
name = "moonwalk_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
raw-window-handle = "0.6"
wgpu = "24.0"
pollster = "0.3"
thiserror = "1.0"
bytemuck = { version = "1.14", features = ["derive"] }
image = "0.25.9"