[package]
name = "lunar3d"
version = "0.2.1"
edition = "2021"

[dependencies]
glam = { version = "0.24", features = ["bytemuck"] }
bytemuck = { version = "1.16", features = ["derive"] }
tobj = "4.0"
gltf = "1.0"
moonwalk = { path = "../moonwalk" }
